### ISSUE TITLE
No support for Alpine Linux

### ISSUE THREAD

**Issue by dirkmoors** [DataDog/datadog-process-agent#107]
Hello,

I would like to use the process agent inside an Alpine Linux environment (inside Docker container). This does not work at the moment.

**Comment by sunhay** [comment]
Hi @dirkmoors! 

Have you tried the latest versions of our docker image? ([5.22.0](https://hub.docker.com/r/datadog/docker-dd-agent/tags/), or [6.rc1](https://hub.docker.com/r/datadog/agent/tags)). We've included a lot of fixes for the process-agent in these new versions.

If it still continues to not work, please open a ticket with support@datadoghq.com so we can gather more details and work on a fix!

- Sunny

**Comment by coretemp** [comment]
@sunhay Would it perhaps be possible for you to act less passive? All you are doing is transferring the cost of debugging your product to other companies, which is about the worst possible behavior a company can have.

**Comment by sunhay** [comment]
Hi! 

Closing this out - feel free to reach out to support@datadoghq.com if this is still an issue that you're dealing with so we can gather more details.

- Sunny
