### ISSUE TITLE
Unclear installation documentation

### ISSUE THREAD

**Issue by domenkozar** [DataDog/datadog-process-agent#182]
I'm trying to package datadog v6, but I can't find documentation how to get live process collection working.

Should this package be compiled and available at `$PATH` so that datadog-agent can invoke it?

I do see

```
UTC | INFO | (serializer.go:263 in SendJSONToV1Intake) | Sent processes metadata payload, size: 1220 bytes.
```

without using this package and no error about missing `datadog-process-agent`.

**Comment by ian28223** [comment]
the process-agent should already be packaged along with the Datadog agent installation. It is, however, disabled by default. Enable it in /etc/datadog-agent/datadog.yaml file and restart the agent.

```
process_config:
  enabled: "true"
```

Alternatively, you can enable it via environment variable DD_PROCESS_AGENT_ENABLED=true. Still need to restart the agent though.

**Comment by coretemp** [comment]
@ian28223 Your advice is wrong. Can you please *test* your advice before you give any in the future? 

(For context, @ian28223 is a Datadog employee).

**Comment by domenkozar** [comment]
@coretemp be nice :) 

I think there are multiple puzzles here, let me collect some data and write back what I have and what is missing.

**Comment by domenkozar** [comment]
@ian28223 there is still no live process list even with that setting on. I'm compiling datadog-agent 6.4.2 with `"-tags" "ec2 systemd cpython process log"`, with following `datadog.yaml`:

```
additional_checksd: /etc/datadog-agent/checks.d
api_key: ''
confd_path: /etc/datadog-agent/conf.d
dd_url: https://app.datadoghq.com
hostname: redacted
logs_enabled: true
process_config:
  enabled: 'true'
skip_ssl_validation: 'no'
tags: staging
use_dogstatsd: true
```

where api key is provided as environment variable. I do not see anything mention process running `datadog configcheck`.

**Comment by sunhay** [comment]
Hi @domenkozar!

At the moment, the `process-agent` currently runs as a separate binary and is not invoked by the main `datadog-agent`. Once the `process-agent` binary has been compiled, you'll just need to pass it the path to your datadog yaml config file. 

e.g.  `$ process-agent --config=<path-to-datadog.yaml>`

As it sounds like you're doing your own packaging of the agent, I'd suggest building it via our included `Rakefile`, which should also inject some git/go version metadata which will be useful for debugging. 

**Example build command for 6.4.1**
```
$ export PROCESS_AGENT_VERSION=6.4.1
$ git checkout $PROCESS_AGENT_VERSION && rake deps build
...
go build -a -o process-agent -tags 'docker kubelet kubeapiserver' -ldflags "-X 'main.Version=6.4.1' -X 'main.BuildDate=2018-09-11T05:18:19+0000' -X 'main.GitCommit=ad7498d' -X 'main.GitBranch=HEAD' -X 'main.GoVersion=go version go1.10.1 linux/amd64'" github.com/DataDog/datadog-process-agent/agent
```

In general, we use [omnibus](https://github.com/DataDog/datadog-agent/tree/master/omnibus) to create our prepackaged binaries, so the packaging scripts there may be useful if you run into any roadblocks, though feel free to let me know if you have any questions

**Comment by domenkozar** [comment]
Hey @sunhay, thank you :) I wonder, would it be possible to have the same packaging lock file for Go dependencies as in datadog-agent? There's no automation for glide/rake I could use.

**Comment by domenkozar** [comment]
Seems like it's not that much work:

``
I've installed dep 0.5.0 and ran:

```
mkdir -p src/github.com/DataDog/datadog-process-agent
export GOPATH=`pwd`
git clone https://github.com/DataDog/datadog-process-agent.git src/github.com/DataDog/datadog-process-agent
cd src/github.com/DataDog/datadog-process-agent
dep init
```

**Comment by sunhay** [comment]
Yes, moving from glide -> dep has been something we've been wanting to do for consistency. I'll see if I can get a PR up and tested :)

**Comment by domenkozar** [comment]
Thanks, managed to get everything working at: https://github.com/NixOS/nixpkgs/pull/46576/files

I'd recommend adding one sentence to https://docs.datadoghq.com/graphing/infrastructure/process/?tab=linuxwindows saying that one should make sure that `agent` is ran from this package.

**Comment by sunhay** [comment]
Awesome! Yes, I'll add a note to modify our docs. Thanks!

Closing this issue for now. Feel free to open another one if any issues pop up.
