### ISSUE TITLE
Glide.yaml - Missing DataDog/datadog-agent repo

### ISSUE THREAD

**Issue by eosrei** [DataDog/datadog-process-agent#52]
https://github.com/DataDog/datadog-process-agent/blob/42c9fd1ec3bd1a7fd38564c7eb0af1e60de9b423/glide.yaml#L3-L6
 
https://github.com/DataDog/datadog-agent does not exist:
![404](https://user-images.githubusercontent.com/195061/29848907-57abb760-8cd8-11e7-987b-6f18954e3f58.png)

**Comment by conorbranagan** [comment]
Now that this agent is open source (https://github.com/DataDog/datadog-agent), the URL and building should work. Closing now but please re-open if you are still having trouble building it

**Comment by eosrei** [comment]
Thanks!
